//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Power_Billing_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int FormID { get; set; }
        public string Name { get; set; }
        public int Gsm { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public System.DateTime TicketDate { get; set; }
        public string Status { get; set; }
    }
}
