//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Power_Billing_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCompany
    {
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> TotalCustomers { get; set; }
        public string Country { get; set; }
    }
}
